---
output:
  html_document:
    self_contained: no
    theme: cosmo
    includes:
      before_body: header.html
  pdf_document: default
---
# Honors College Environment

## Locations
Always use wired connections if possible.

The Honors College has two locations, in the M.D. Anderson Library and the basement of Moody Towers (Honors Gardens). The Library houses the Dean's office, recruitment and student services offices, and several faculty offices and classrooms. The Gardens houses the Bonner Leaders program (Bonner Base), Honors Program in the Health Professions (HP2), DASH and the Center for Creative Work (CCW).

## Network Topology
 

The University of Houston's IT department controls the network topology of the entire campus. The Honors College has been allocated the 172.27.56.0/24 subnet for the MD Anderson Library and the 172.27.219.0/24 subnet for the Honors Gardens. All IP addresses are assigned by DHCP, but static addresses can be specified. Both locations use 100 Mbit/sec Ethernet.